from utils.llm_client import LLMClient
from core.prompts import BUILDER_V1

class Builder:
    """
    The Actor Agent.
    Role: Reads a Technical Spec and writes the implementation code.
    Goal: Produce code that passes the Critic's behavioral tests.
    """
    
    def __init__(self, llm_client: LLMClient = None):
        self.llm = llm_client or LLMClient()

    def build(self, spec_content: str, prompt_template: str = BUILDER_V1) -> str:
        """
        Generates Python code from the provided specification.
        
        Args:
            spec_content: The full markdown spec generated by the SpecWriter.
            prompt_template: The system instructions (defaults to V1).
            
        Returns:
            Clean, executable Python code string.
        """
        user_prompt = f"### TECHNICAL SPECIFICATION:\n{spec_content}"
        
        # CLEAN: No hardcoded temperature here anymore
        return self.llm.complete(prompt_template, user_prompt)